"""Schema codegen — reads the IDL and emits TS + Python generated files.

Usage::

    python -m learning_service.schema.codegen            # write generated files
    python -m learning_service.schema.codegen --check    # exit 1 if stale

The ``--check`` flag is what CI runs.  It regenerates the output in memory,
diffs against what is on disk, and exits 1 (printing a diff) if anything is
out of date.

Generated files:
  packages/learning-service/src/learning_service/schema/generated/py_types.py
  packages/learning-service/src/learning_service/schema/generated/ts_types.ts
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import sys
import textwrap
from pathlib import Path

from learning_service.schema.idl import SCHEMA, KeyDef, RecordDef, FieldDef

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_HERE = Path(__file__).parent
# The repo root is 5 levels up from the schema/ directory:
#   schema/ → learning_service/ → src/ → learning-service/ → packages/ → repo_root
_REPO_ROOT = _HERE.parent.parent.parent.parent.parent

GENERATED_DIR = _HERE / "generated"
PY_OUT = GENERATED_DIR / "py_types.py"
TS_OUT = GENERATED_DIR / "ts_types.ts"

# The shared-package re-export (Gap 2 of MAT-141):
# packages/shared/src/learning-schema.ts is also generated by this script so
# @harness/shared can export the IDL-generated key builders + record interfaces
# without consumers depending directly on packages/learning-service.
SHARED_TS_OUT = _REPO_ROOT / "packages" / "shared" / "src" / "learning-schema.ts"

# A short fingerprint of the IDL embedded in generated headers so a simple
# grep can confirm which IDL version produced a file.
def _idl_fingerprint() -> str:
    import importlib.util
    idl_path = _HERE / "idl.py"
    content = idl_path.read_bytes()
    return hashlib.sha256(content).hexdigest()[:16]


# ---------------------------------------------------------------------------
# Python generator
# ---------------------------------------------------------------------------

def _py_field_annotation(f: FieldDef) -> str:
    mapping = {
        "str": "str",
        "str?": "str | None",
        "int": "int",
        "int?": "int | None",
        "float": "float",
        "float?": "float | None",
        "bool": "bool",
        "bool?": "bool | None",
        "str[]": "list[str]",
    }
    return mapping[f.kind]


def _py_field_default(f: FieldDef) -> str:
    if f.optional or f.kind.endswith("?"):
        return " = None"
    if f.kind == "str[]":
        return " = field(default_factory=list)"
    return ""


def generate_python(schema=SCHEMA) -> str:
    fp = _idl_fingerprint()
    lines: list[str] = [
        '"""GENERATED — do not edit by hand.',
        "",
        "This file is produced by ``learning_service.schema.codegen``.",
        f"IDL fingerprint: {fp}  (schema version {schema.version})",
        "",
        "Regenerate with:",
        "    python -m learning_service.schema.codegen",
        "",
        "CI freshness check:",
        "    python -m learning_service.schema.codegen --check",
        '"""',
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass, field",
        "",
    ]

    # Pad helper
    lines += [
        "# ---------------------------------------------------------------------------",
        "# Pad widths (mirrored from the IDL)",
        "# ---------------------------------------------------------------------------",
        "",
    ]
    for name, width in schema.pad_widths.items():
        lines.append(f"PAD_{name.upper()} = {width}")
    lines.append("")

    def _pad_expr(template_var: str, pad_name: str) -> str:
        width = schema.pad_widths.get(pad_name)
        if width is None:
            return f"str({template_var})"
        return f"str({template_var}).zfill({width})"

    # Key builders
    lines += [
        "# ---------------------------------------------------------------------------",
        "# Key builders",
        "# ---------------------------------------------------------------------------",
        "",
    ]
    for kd in schema.key_defs:
        # Build the function signature
        params = ", ".join(f"{p}: str | int" for p in kd.params)
        lines.append(f"def {kd.name}({params}) -> dict[str, str]:")
        if kd.description:
            lines.append(f'    """{kd.description}"""')

        # Render PK / SK templates
        def _render(template: str, params: list[str]) -> str:
            # Replace {name} → {name} (plain), {name:pad} → zero-padded
            result = template
            import re
            for m in re.finditer(r"\{(\w+)(?::(\w+))?\}", template):
                var, pad = m.group(1), m.group(2)
                if pad:
                    width = schema.pad_widths.get(pad, 12)
                    result = result.replace(m.group(0), f"{{str({var}).zfill({width})}}")
                else:
                    result = result.replace(m.group(0), f"{{{var}}}")
            return result

        pk_expr = _render(kd.pk_template, kd.params)
        sk_expr = _render(kd.sk_template, kd.params)
        lines.append(f'    return {{"PK": f"{pk_expr}", "SK": f"{sk_expr}"}}')
        lines.append("")

    # Record dataclasses
    lines += [
        "# ---------------------------------------------------------------------------",
        "# Record dataclasses",
        "# ---------------------------------------------------------------------------",
        "",
    ]
    for rd in schema.record_defs:
        lines.append("@dataclass")
        lines.append(f"class {rd.name}:")
        if rd.description:
            lines.append(f'    """{rd.description}"""')
        for fld in rd.fields:
            ann = _py_field_annotation(fld)
            default = _py_field_default(fld)
            comment = f"  # {fld.description}" if fld.description else ""
            if "field(default_factory" in default:
                lines.append(f"    {fld.name}: {ann} = field(default_factory=list){comment}")
            else:
                lines.append(f"    {fld.name}: {ann}{default}{comment}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# TypeScript generator
# ---------------------------------------------------------------------------

def _ts_field_type(f: FieldDef) -> str:
    mapping = {
        "str": "string",
        "str?": "string | undefined",
        "int": "number",
        "int?": "number | undefined",
        "float": "number",
        "float?": "number | undefined",
        "bool": "boolean",
        "bool?": "boolean | undefined",
        "str[]": "string[]",
    }
    return mapping[f.kind]


def generate_typescript(schema=SCHEMA) -> str:
    fp = _idl_fingerprint()
    lines: list[str] = [
        "/**",
        " * GENERATED — do not edit by hand.",
        " *",
        " * Produced by learning_service.schema.codegen.",
        f" * IDL fingerprint: {fp}  (schema version {schema.version})",
        " *",
        " * Regenerate:",
        " *   python -m learning_service.schema.codegen",
        " *",
        " * CI freshness check:",
        " *   python -m learning_service.schema.codegen --check",
        " */",
        "",
    ]

    # Pad width consts
    lines += [
        "// ---------------------------------------------------------------------------",
        "// Pad widths (mirrored from the IDL)",
        "// ---------------------------------------------------------------------------",
        "",
    ]
    for name, width in schema.pad_widths.items():
        lines.append(f"export const PAD_{name.upper()} = {width} as const;")
    lines.append("")

    # Pad helper
    lines += [
        "const _pad = (n: number, width: number): string =>",
        "  String(Math.trunc(n)).padStart(width, '0');",
        "",
    ]

    def _ts_render(template: str, params: list[str]) -> str:
        import re
        result = template
        for m in re.finditer(r"\{(\w+)(?::(\w+))?\}", template):
            var, pad_name = m.group(1), m.group(2)
            if pad_name:
                width = schema.pad_widths.get(pad_name, 12)
                result = result.replace(m.group(0), f"${{_pad(Number({var}), {width})}}")
            else:
                result = result.replace(m.group(0), f"${{{var}}}")
        return result

    # Key builders
    lines += [
        "// ---------------------------------------------------------------------------",
        "// Key builders",
        "// ---------------------------------------------------------------------------",
        "",
    ]
    for kd in schema.key_defs:
        params_sig = ", ".join(f"{p}: string | number" for p in kd.params)
        pk_expr = _ts_render(kd.pk_template, kd.params)
        sk_expr = _ts_render(kd.sk_template, kd.params)
        if kd.description:
            lines.append(f"/** {kd.description} */")
        lines.append(f"export const {_camel(kd.name)} = ({params_sig}): {{ PK: string; SK: string }} => ({{")
        lines.append(f"  PK: `{pk_expr}`,")
        lines.append(f"  SK: `{sk_expr}`,")
        lines.append("});")
        lines.append("")

    # Interfaces
    lines += [
        "// ---------------------------------------------------------------------------",
        "// Record interfaces",
        "// ---------------------------------------------------------------------------",
        "",
    ]
    for rd in schema.record_defs:
        if rd.description:
            lines.append(f"/** {rd.description} */")
        lines.append(f"export interface {rd.name} {{")
        for fld in rd.fields:
            ts_type = _ts_field_type(fld)
            optional_marker = "?" if fld.optional or fld.kind.endswith("?") else ""
            comment = f"  // {fld.description}" if fld.description else ""
            lines.append(f"  {fld.name}{optional_marker}: {ts_type};{comment}")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def _camel(snake: str) -> str:
    """Convert snake_case to camelCase."""
    parts = snake.split("_")
    return parts[0] + "".join(p.title() for p in parts[1:])


def generate_shared_typescript(schema=SCHEMA) -> str:
    """Generate the packages/shared/src/learning-schema.ts re-export.

    This mirrors the same key builders and interfaces as ts_types.ts but:
    - Uses a ``Learning``-prefixed namespace for type names (to avoid clashing
      with the hand-authored @harness/shared types like Skill, GoldenCase).
    - Uses ``learning``-prefixed function names for key builders.
    - Embeds a clear header explaining the file is generated and where the
      canonical source is.

    Gap 2 of MAT-141: makes @harness/shared the single TS import point for
    the IDL-generated schema, replacing any hand-authored mirror.
    """
    fp = _idl_fingerprint()
    lines: list[str] = [
        "/**",
        " * GENERATED — do not edit by hand.",
        " *",
        " * This file re-exports the learning-service IDL-generated schema types into",
        " * @harness/shared so TS consumers (packages/backend, packages/web, the Go",
        " * wrapper's golden fixture) can import the single-source-of-truth key builders",
        " * and record interfaces without depending directly on packages/learning-service.",
        " *",
        " * The canonical source is:",
        " *   packages/learning-service/src/learning_service/schema/generated/ts_types.ts",
        " *",
        " * Regenerate the canonical source with:",
        " *   python -m learning_service.schema.codegen",
        " *",
        " * CI freshness check:",
        " *   python -m learning_service.schema.codegen --check",
        " *",
        " * The codegen also writes this file (packages/shared/src/learning-schema.ts) so",
        " * both copies are always in sync.  If they diverge, CI fails.",
        " *",
        f" * IDL fingerprint: {fp}  (schema version {schema.version})",
        " */",
        "",
        "// ---------------------------------------------------------------------------",
        "// Pad widths (mirrored from the IDL)",
        "// ---------------------------------------------------------------------------",
        "",
    ]
    for name, width in schema.pad_widths.items():
        lines.append(f"export const PAD_{name.upper()} = {width} as const;")
    lines.append("")

    # Pad helper
    lines += [
        "const _pad = (n: number, width: number): string =>",
        "  String(Math.trunc(n)).padStart(width, '0');",
        "",
        "// ---------------------------------------------------------------------------",
        "// Key builders  (org-scope single-table design — SCOPE#org#<org> PK)",
        "// ---------------------------------------------------------------------------",
        "",
    ]

    def _ts_render(template: str, params: list[str]) -> str:
        import re
        result = template
        for m in re.finditer(r"\{(\w+)(?::(\w+))?\}", template):
            var, pad_name = m.group(1), m.group(2)
            if pad_name:
                width = schema.pad_widths.get(pad_name, 12)
                result = result.replace(m.group(0), f"${{_pad(Number({var}), {width})}}")
            else:
                result = result.replace(m.group(0), f"${{{var}}}")
        return result

    for kd in schema.key_defs:
        params_sig = ", ".join(f"{p}: string | number" for p in kd.params)
        pk_expr = _ts_render(kd.pk_template, kd.params)
        sk_expr = _ts_render(kd.sk_template, kd.params)
        fn_name = "learning" + _camel(kd.name)[0].upper() + _camel(kd.name)[1:]
        if kd.description:
            lines.append(f"/** {kd.description} */")
        lines.append(f"export const {fn_name} = ({params_sig}): {{ PK: string; SK: string }} => ({{")
        lines.append(f"  PK: `{pk_expr}`,")
        lines.append(f"  SK: `{sk_expr}`,")
        lines.append("});")
        lines.append("")

    lines += [
        "// ---------------------------------------------------------------------------",
        "// Record interfaces  (generated from IDL — single source of truth)",
        "// ---------------------------------------------------------------------------",
        "",
    ]

    for rd in schema.record_defs:
        prefixed_name = "Learning" + rd.name
        if rd.description:
            lines.append(f"/** {rd.description} */")
        lines.append(f"export interface {prefixed_name} {{")
        for fld in rd.fields:
            ts_type = _ts_field_type(fld)
            optional_marker = "?" if fld.optional or fld.kind.endswith("?") else ""
            comment = f"  // {fld.description}" if fld.description else ""
            lines.append(f"  {fld.name}{optional_marker}: {ts_type};{comment}")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Write / check
# ---------------------------------------------------------------------------

def _ensure_generated_dir() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    init = GENERATED_DIR / "__init__.py"
    if not init.exists():
        init.write_text(
            '"""Generated schema types — do not edit by hand."""\n',
            encoding="utf-8",
        )


def write_generated() -> None:
    """Regenerate all three output files in place."""
    _ensure_generated_dir()
    py_src = generate_python()
    ts_src = generate_typescript()
    shared_ts_src = generate_shared_typescript()
    PY_OUT.write_text(py_src, encoding="utf-8")
    TS_OUT.write_text(ts_src, encoding="utf-8")
    if SHARED_TS_OUT.exists() or SHARED_TS_OUT.parent.exists():
        SHARED_TS_OUT.write_text(shared_ts_src, encoding="utf-8")
        print(f"Written: {SHARED_TS_OUT}")
    else:
        print(f"SKIPPED (parent dir missing): {SHARED_TS_OUT}")
    print(f"Written: {PY_OUT}")
    print(f"Written: {TS_OUT}")


def check_freshness() -> bool:
    """Return True if all generated files are up-to-date, False if stale.

    Prints a unified diff to stdout for any stale file.

    Checks:
    1. py_types.py
    2. ts_types.ts
    3. packages/shared/src/learning-schema.ts  (Gap 2 of MAT-141)
    """
    fresh = True
    py_src = generate_python()
    ts_src = generate_typescript()
    shared_ts_src = generate_shared_typescript()

    pairs = [(PY_OUT, py_src), (TS_OUT, ts_src)]
    # Only check the shared TS file if it exists (it may be absent in learning-service-only
    # CI runs that haven't checked out the full monorepo).
    if SHARED_TS_OUT.exists():
        pairs.append((SHARED_TS_OUT, shared_ts_src))

    for path, expected in pairs:
        if not path.exists():
            print(f"MISSING: {path}")
            fresh = False
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            diff = difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(path) + " (on disk)",
                tofile=str(path) + " (expected)",
            )
            print(f"STALE: {path}")
            print("".join(diff))
            fresh = False

    return fresh


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Codegen: IDL → generated/py_types.py + generated/ts_types.ts",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check freshness only; exit 1 if stale (CI mode).",
    )
    args = parser.parse_args(argv)

    if args.check:
        ok = check_freshness()
        if not ok:
            print(
                "\nRun `python -m learning_service.schema.codegen` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print("Schema codegen output is up-to-date.")
        return 0
    else:
        write_generated()
        return 0


if __name__ == "__main__":
    sys.exit(main())
