// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function Focus(arg1) {
  return window['go']['main']['App']['Focus'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function Resize(arg1, arg2) {
  return window['go']['main']['App']['Resize'](arg1, arg2);
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}

export function StartupError() {
  return window['go']['main']['App']['StartupError']();
}
