// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Focus(arg1) {
  return window['go']['main']['App']['Focus'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function Resize(arg1, arg2) {
  return window['go']['main']['App']['Resize'](arg1, arg2);
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}

export function StartupError() {
  return window['go']['main']['App']['StartupError']();
}
