// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {daemon} from '../models';

export function Focus(arg1:string):Promise<void>;

export function ListSessions():Promise<Array<daemon.SessInfo>>;

export function NewSession():Promise<void>;

export function Resize(arg1:number,arg2:number):Promise<void>;

export function SendInput(arg1:string):Promise<void>;

export function StartupError():Promise<string>;
